import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import cv2

from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from utils.gradcam import generate_gradcam

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Comprehensive Retinal Analysis",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_retina_model():
    return tf.keras.models.load_model("model/best_retina_model.h5")

model = load_retina_model()

# ✅ MUST MATCH ODIR-5K (8 classes)
CLASS_NAMES = [
    "Normal",
    "Diabetes",
    "Glaucoma",
    "Cataract",
    "AMD",
    "Hypertension",
    "Myopia",
    "Other"
]

# ---------------- SIDEBAR ----------------
st.sidebar.title("🩺 Retinal AI System")
st.sidebar.markdown("""
AI-based retinal disease screening and analysis system.

**Features**
• CNN (MobileNetV2)  
• Explainable AI (Grad-CAM)  
• Severity scoring  
• PDF medical reports  
""")

st.sidebar.markdown("---")
patient_id = st.sidebar.text_input("Patient ID", value="PAT-001")

uploaded_file = st.sidebar.file_uploader(
    "Upload Retinal Fundus Image",
    type=["jpg", "jpeg", "png"]
)

# ---------------- HEADER ----------------
st.title("Comprehensive Retinal Analysis – Medical Dashboard")
st.caption("AI-assisted retinal screening with explainability and reporting")
st.markdown("---")

# ---------------- PDF REPORT FUNCTION ----------------
def generate_medical_report(
    patient_id,
    diagnosis,
    confidence,
    severity,
    timestamp
):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 800, "Comprehensive Retinal Analysis – Medical Report")

    c.setFont("Helvetica", 11)
    c.drawString(50, 760, f"Patient ID: {patient_id}")
    c.drawString(50, 740, f"Date & Time: {timestamp}")

    c.line(50, 720, 550, 720)

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, 690, "Diagnosis Summary")

    c.setFont("Helvetica", 11)
    c.drawString(50, 660, f"Detected Condition: {diagnosis}")
    c.drawString(50, 640, f"Confidence Score: {confidence*100:.2f}%")
    c.drawString(50, 620, f"Severity Level: {severity}")

    c.line(50, 600, 550, 600)

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, 570, "Clinical Notes")

    c.setFont("Helvetica", 11)
    c.drawString(50, 545, "This report is generated by an AI-based retinal screening system.")
    c.drawString(50, 525, "Highlighted regions indicate areas influencing the AI decision.")
    c.drawString(50, 505, "⚠ This system is intended for decision support only.")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

# ---------------- MAIN LOGIC ----------------
if uploaded_file is not None:

    # Load & preprocess image
    image = Image.open(uploaded_file).convert("RGB")
    img_resized = image.resize((224, 224))
    img_array = np.array(img_resized) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Prediction
    preds = model.predict(img_array)
    preds = preds.flatten()  # 🔒 safety
    class_idx = np.argmax(preds)
    confidence = preds[class_idx]

    # Severity logic
    if confidence < 0.5:
        severity = "Mild"
    elif confidence < 0.75:
        severity = "Moderate"
    else:
        severity = "Severe"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Grad-CAM
    heatmap = generate_gradcam(model, img_array)

    heatmap_color = cv2.applyColorMap(
        np.uint8(255 * heatmap), cv2.COLORMAP_JET
    )
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)

    overlay = cv2.addWeighted(
        np.array(img_resized), 0.6, heatmap_color, 0.4, 0
    )

    # ---------------- METRICS ----------------
    col1, col2, col3 = st.columns(3)
    col1.metric("Detected Condition", CLASS_NAMES[class_idx])
    col2.metric("Confidence", f"{confidence*100:.2f}%")
    col3.metric("Severity", severity)

    st.markdown("---")

    # ---------------- IMAGE PANELS (FIXED ALIGNMENT) ----------------
    c1, c2, c3 = st.columns([1, 1, 1], gap="large")

    with c1:
        st.subheader("Original Retinal Image")
        st.image(image, width=300)

    with c2:
        st.subheader("Abnormality Heatmap")
        fig, ax = plt.subplots()
        ax.imshow(heatmap, cmap="jet")
        ax.axis("off")
        st.pyplot(fig)

    with c3:
        st.subheader("Heatmap Overlay")
        st.image(overlay, width=300)

    st.markdown("---")

    # ---------------- PROBABILITY CHART (FIXED) ----------------
    st.subheader("Disease Probability Distribution")

    sorted_idx = np.argsort(preds)
    sorted_probs = preds[sorted_idx]
    sorted_classes = [CLASS_NAMES[i] for i in sorted_idx]

    fig2, ax2 = plt.subplots(figsize=(6, 4))
    ax2.barh(sorted_classes, sorted_probs)
    ax2.set_xlim(0, 1)
    ax2.set_xlabel("Probability")
    ax2.set_title("Disease Probability Distribution")

    st.pyplot(fig2)

    # ---------------- CLINICAL NOTE ----------------
    st.subheader("📝 Clinical Interpretation")
    st.info(
        f"The AI model predicts **{CLASS_NAMES[class_idx]}** "
        f"with **{confidence*100:.2f}% confidence**. "
        "Highlighted regions indicate influential retinal areas."
    )

    # ---------------- PDF DOWNLOAD ----------------
    st.markdown("---")
    st.subheader("📄 Download Medical Report")

    pdf_buffer = generate_medical_report(
        patient_id,
        CLASS_NAMES[class_idx],
        confidence,
        severity,
        timestamp
    )

    st.download_button(
        label="Download PDF Medical Report",
        data=pdf_buffer,
        file_name=f"{patient_id}_retinal_report.pdf",
        mime="application/pdf"
    )

else:
    st.info("⬅ Upload a retinal image from the sidebar to begin analysis.")
